// Generated by scripts/generate-eras.mjs (Phase C). Committed empty stub so the
// gallery/timeline compile before the generator runs; ERAS = [] → no era facet.
export type MilestoneKey = "stock_tank" | "raised_beds" | "cedar_planters" | "vines" | "cover_crop_field";

export type EraContent = {
  key: string;
  title: string;
  blurb: string;
  milestones: MilestoneKey[];
  start: string;
  end: string | null;
  coverPath: string | null;
  generatedAt: string;
  model: string;
};

export const ERAS: EraContent[] = [];
