// Generated by scripts/generate-eras.mjs — do not edit by hand.
export type MilestoneKey = "stock_tank" | "raised_beds" | "cedar_planters" | "vines" | "cover_crop_field";

export type EraContent = {
  key: string;
  title: string;
  blurb: string;
  milestones: MilestoneKey[];
  start: string;
  end: string | null;
  coverPath: string | null;
  generatedAt: string;
  model: string;
};

export const ERAS: EraContent[] = [
  {"key":"era-0","title":"The Yard as Found","blurb":"This chapter captures the established yard before any major additions — the kidney-shaped pool, brick house facades, mature oak trees, and foundation shrubs all documented in their original state. A complete baseline portrait of the property, from the front lawn's deep shade to the pool equipment tucked along the side passage.","milestones":[],"start":"2024-10-17T16:45:05+00:00","end":"2025-04-13T16:05:26+00:00","coverPath":"75e5b8a1-0db0-47e5-9ccb-73881fd50dff/0fe9c66e-81f5-4484-9de0-1799ded44806.jpg","generatedAt":"2026-07-12T20:33:38.134Z","model":"claude-sonnet-4-6"},
  {"key":"era-1","title":"Beds, Tanks & Vines","blurb":"Spring planting hit its stride as raised beds, cedar planters, and a stock tank took shape alongside new arrivals of vines, lavender, and salvia. Color swept across the yard in waves of purple, red, and blue, while drip lines and fresh mulch anchored each new planting into place.","milestones":["stock_tank","raised_beds","cedar_planters","vines"],"start":"2025-04-13T16:05:26+00:00","end":"2025-05-18T13:00:31+00:00","coverPath":"75e5b8a1-0db0-47e5-9ccb-73881fd50dff/ba25e291-a6e6-4c4d-9ce8-c095df4a9769.jpg","generatedAt":"2026-07-12T20:33:38.134Z","model":"claude-sonnet-4-6"},
  {"key":"era-2","title":"Seeded, Planted, Buzzing","blurb":"A cover-crop field took shape in the south lawn as bare soil gave way to seeded ground and freshly mulched beds, while new transplants went in along the hellstrip and fence lines. The yard wore its work openly — flags, flags, drip lines, and survey markers — inviting pollinators into every corner still finding its footing.","milestones":["cover_crop_field"],"start":"2025-05-18T13:00:31+00:00","end":null,"coverPath":"75e5b8a1-0db0-47e5-9ccb-73881fd50dff/8e3a079f-95c2-4874-a778-4f08b7d72184.jpg","generatedAt":"2026-07-12T20:33:38.134Z","model":"claude-sonnet-4-6"}
];
