// scripts/generate-eras.mjs
import { config } from "dotenv";
import { writeFile } from "node:fs/promises";
import Anthropic from "@anthropic-ai/sdk";
import { createClient } from "@supabase/supabase-js";
import { buildEras, defaultEraTitle, MILESTONES } from "../src/lib/eras.mjs";

config({ path: ".env.local" });
config();

const MODEL = "claude-sonnet-4-6";
const DRY = process.argv.includes("--dry-run");

function requireEnv(name) {
  const v = process.env[name];
  if (!v) { console.error(`Missing ${name}`); process.exit(1); }
  return v;
}

async function loadConfirmed(sb) {
  const out = [];
  for (let from = 0; ; from += 1000) {
    const { data, error } = await sb.from("zone_photos")
      .select("id, storage_path, taken_at, uploaded_at, caption, ai_confidence, ai_meta")
      .eq("review_status", "confirmed").order("taken_at", { ascending: true })
      .order("id", { ascending: true })
      .range(from, from + 999);
    if (error) throw error;
    out.push(...data);
    if (data.length < 1000) break;
  }
  return out;
}

function eraPhotos(photos, era) {
  return photos.filter((p) => {
    const d = p.taken_at ?? p.uploaded_at;
    return d >= era.start && (era.end === null || d < era.end);
  });
}

function digest(photos, era) {
  const inEra = eraPhotos(photos, era);
  const captions = inEra.filter((p) => p.caption).slice(0, 20).map((p) => `- ${p.caption}`);
  const bloom = new Set();
  for (const p of inEra) for (const c of p.ai_meta?.botanical?.bloom_colors ?? []) bloom.add(c);
  const ms = era.milestones.map((k) => MILESTONES.find((m) => m.key === k)?.label ?? k);
  return {
    count: inEra.length,
    range: `${era.start.slice(0, 10)} → ${era.end ? era.end.slice(0, 10) : "present"}`,
    milestones: ms,
    bloomColors: [...bloom].slice(0, 12),
    captionSample: captions.join("\n"),
    cover: inEra.slice().sort((a, b) => (b.ai_confidence ?? 0) - (a.ai_confidence ?? 0))[0]?.storage_path ?? null,
  };
}

const SCHEMA = {
  type: "object", additionalProperties: false,
  properties: { title: { type: "string" }, blurb: { type: "string" } },
  required: ["title", "blurb"],
};

function promptFor(d) {
  return `You are titling one chapter of a residential yard's photo timeline.
Date range: ${d.range}. Photos: ${d.count}. New this chapter: ${d.milestones.join(", ") || "(the established yard, before major additions)"}.
Bloom colors seen: ${d.bloomColors.join(", ") || "none noted"}.
Sample captions:
${d.captionSample || "(none)"}

Return JSON: a short evocative "title" (2-4 words, no date) and a "blurb" (1-2 sentences, past/present tense, describing what changed or what the yard was like this chapter). Do not invent features not implied by the milestones or captions.`;
}

async function headline(anthropic, d) {
  const msg = await anthropic.messages.create({
    model: MODEL, max_tokens: 300,
    messages: [{ role: "user", content: promptFor(d) }],
    output_config: { format: { type: "json_schema", schema: SCHEMA } },
  });
  const block = msg.content.find((b) => b.type === "text");
  return JSON.parse(block ? block.text : "{}");
}

function fileContents(eras) {
  const body = eras.map((e) => "  " + JSON.stringify(e)).join(",\n");
  return `// Generated by scripts/generate-eras.mjs — do not edit by hand.
export type MilestoneKey = "stock_tank" | "raised_beds" | "cedar_planters" | "vines" | "cover_crop_field";

export type EraContent = {
  key: string;
  title: string;
  blurb: string;
  milestones: MilestoneKey[];
  start: string;
  end: string | null;
  coverPath: string | null;
  generatedAt: string;
  model: string;
};

export const ERAS: EraContent[] = [
${body}
];
`;
}

async function main() {
  const sb = createClient(requireEnv("NEXT_PUBLIC_SUPABASE_URL"), requireEnv("SUPABASE_SERVICE_ROLE_KEY"), { auth: { persistSession: false } });
  const photos = await loadConfirmed(sb);
  const eras = buildEras(photos);
  const now = new Date().toISOString();

  const anthropic = DRY ? null : new Anthropic({ apiKey: requireEnv("ANTHROPIC_API_KEY") });
  const out = [];
  for (const era of eras) {
    const d = digest(photos, era);
    if (DRY) { console.log(`\n[${era.key}] ${d.range} (${d.count} photos) ms=${d.milestones.join(",")||"—"}`); console.log(promptFor(d)); continue; }
    let title, blurb;
    try { ({ title, blurb } = await headline(anthropic, d)); }
    catch (err) { console.warn(`headline failed for ${era.key}: ${err.message}; using fallback`); title = defaultEraTitle(era); blurb = ""; }
    out.push({ key: era.key, title, blurb, milestones: era.milestones, start: era.start, end: era.end, coverPath: d.cover, generatedAt: now, model: MODEL });
    console.log(`✓ ${era.key}: ${title}`);
  }

  if (DRY) { console.log(`\n(dry run — ${eras.length} eras; wrote nothing)`); return; }
  await writeFile("src/lib/eras.data.ts", fileContents(out));
  console.log(`Wrote src/lib/eras.data.ts (${out.length} eras).`);
}

main().catch((e) => { console.error(e); process.exit(1); });
